version: '3'
services:
  server_restarter:
    container_name: server_restarter
    image: danacr/server-restarter:latest
    devices:
      - /dev/hidraw0:/dev/hidraw0
    restart: unless-stopped
    ports:
      - 80:80