version: '3'
services:
  server_restarter:
    container_name: server_restarter
    image: homeassistant/home-assistant
    volumes:
      - /dev/hidraw0:/dev/hidraw0:rw
    restart: unless-stopped
    network_mode: host
